version: '3'
services:
  Frontend:
    image: drupal
    ports:
    - 80:80
    deploy:
      replicas: 2
    networks:
    - Jenkinet
  Backend:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=123456
    networks:
    - Jenkinet
networks:
   Jenkinet: